const menuList = [
    {
        name:"首页",
        url:"#",
        show:true,
        subMenus:[]
    },
    {
        name:"我的车",
        url:"#",
        show:true,
        subMenus:[{name:"已买的车",url:"#"},{name:"已卖出的车",url:"#"}]
    },
    {
        name:"收藏夹",
        url:"#",
        show:true,
        subMenus:[{name:"收藏的车",url:"#"}]
    },
    {
        name:"购物车",
        url:"#",
        show:true,
        subMenus:[]
    }
    ]
    const cars_info=[
        {
            imagePath:'./图片/特斯拉modelS.jpg',
            title:'特斯拉',
            author:'张三',
            price:'350000',
            count:0
        },
        {
            imagePath:'./图片/星越L.jpg',
            title:'星越L',
            author:'李四',
            price:'80000',
            count:0
        },
        {
            imagePath:'./图片/雷克萨斯ES.jpg',
            title:'雷克萨斯ES',
            author:'王五',
            price:'370000',
            count:0
        },
        {
            imagePath:'./图片/奥迪A4.jpg',
            title:'奥迪A4',
            author:'赵六',
            price:'200000',
            count:0
        },
        {
            imagePath:'./图片/奥迪A6L.jpg',
            title:'奥迪A6L',
            author:'宋七',
            price:'500000',
            count:0
        },
        {
            imagePath:'./图片/宝马三系.jpg',
            title:'宝马三系',
            author:'李德',
            price:'400000',
            count:0
        }
    ];
