const menuList = [
    {
        name:"首页",
        url:"#",
        show:true,
        subMenus:[]
    },
    {
        name:"我的车",
        url:"#",
        show:true,
        subMenus:[{name:"已买的车",url:"#"},{name:"已卖出的车",url:"#"}]
    },
    {
        name:"收藏夹",
        url:"#",
        show:true,
        subMenus:[{name:"收藏的车",url:"#"}]
    },
    {
        name:"购物车",
        url:"#",
        show:true,
        subMenus:[]
    }
    ]
    const cars_info=[
        {
            imagePath:'./图片/特斯拉modelS.jpg',
            title:'特斯拉',
            owner:'张三',
            phone:'13812345678',
            price:'350000',
            count:0
        },
        {
            imagePath:'./图片/星越L.jpg',
            title:'星越L',
            owner:'李四',
            phone:'13812395678',
            price:'80000',
            count:0
        },
        {
            imagePath:'./图片/雷克萨斯ES.jpg',
            title:'雷克萨斯ES',
            owner:'王五',
            phone:'13812465678',
            price:'370000',
            count:0
        },
        {
            imagePath:'./图片/奥迪A4.jpg',
            title:'奥迪A4',
            owner:'赵六',
            phone:'13812535698',
            price:'200000',
            count:0
        },
        {
            imagePath:'./图片/奥迪A6L.jpg',
            title:'奥迪A6L',
            owner:'宋七',
            phone:'13812605598',
            price:'500000',
            count:0
        },
        {
            imagePath:'./图片/宝马三系.jpg',
            title:'宝马三系',
            owner:'李德',
            phone:'13912675678',
            price:'400000',
            count:0
        }
    ];
