const menuList = [
    {
        name:"首页",
        url:"#",
        show:true,
        subMenus:[]
    },
    {
        name:"我的淘宝",
        url:"#",
        show:true,
        subMenus:[{name:"已买到的宝贝",url:"#"},{name:"已卖出的宝贝",url:"#"}]
    },
    {
        name:"收藏夹",
        url:"#",
        show:true,
        subMenus:[{name:"收藏的宝贝",url:"#"},{name:"收藏的店铺",url:"#"}]
    },
    {
        name:"购物车",
        url:"#",
        show:true,
        subMenus:[]
    }
    ]
    const books_info=[
        {
            imagePath:'./图片/水浒传.jpeg',
            title:'水浒传',
            author:'施耐庵',
            price:'39.9',
            count:0
        },
        {
            imagePath:'./图片/三国演义.jpeg',
            title:'三国演义',
            author:'罗贯中',
            price:'39.9',
            count:0
        },
        {
            imagePath:'./图片/西游记.jpeg',
            title:'西游记',
            author:'吴承恩',
            price:'39.9',
            count:0
        },
        {
            imagePath:'./图片/红楼梦.jpeg',
            title:'红楼梦',
            author:'曹雪芹',
            price:'39.9',
            count:0
        },
        {
            imagePath:'./图片/活着.jpeg',
            title:'活着',
            author:'余华',
            price:'39.9',
            count:0
        },
        {
            imagePath:'./图片/一片叶子落下来.jpeg',
            title:'一片叶子落下来',
            author:'里奥',
            price:'39.9',
            count:0
        }
    ];
